-- Radia HR Platform — Seed Data (Development Only)
-- This file is intentionally empty.
-- All data is created through the app's signup and onboarding flow.
--
-- To seed demo data for local development, use the Supabase dashboard
-- or create records through the running application.
